spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    bootstrap-servers: localhost:19090

security:
  jwt:
    access-token-secret-key: secretkeyfortestchangeitifyouneed
    refresh-token-secret-key: refreshsecretkeyfortestchangeitifyouneed